routes/web.php
Route::get('auto_reject_order', 'CronController@auto_reject_order')->name('auto_reject_order');
Route::get('order_failed', 'CronController@order_failed')->name('order_failed');
Route::get('both_reject', 'CronController@both_reject')->name('both_reject');
Route::get('order_expire', 'CronController@order_expire')->name('order_expire');
Route::get('diet_station', 'CronController@diet_station');
Route::get('invoice/pdf/{id}','InvoiceController@pdf');
Route::get('reminder', 'CronController@reminder');
Route::get('test_booky', 'CronController@test_booky');
Route::get('generate_token/{id}', 'CommonController@generate_token')->name('generate_token');
Route::post('make_payment', 'CommonController@make_payment')->name('make_payment');
Route::get('transaction_fail/{id}', 'CommonController@transaction_fail')->name('transaction_fail');
Route::get('transaction_success/{id}/{id1}', 'CommonController@transaction_success')->name('transaction_success');
// Route::get('transaction_success/{id}', 'CommonController@transaction_success')->name('transaction_success');
Route::get('refund/{id}/{id1}', 'CommonController@refund')->name('refund');
Route::get('payment/card', 'CommonController@save_card')->name('save_card');
Route::post('proceed_to_payment', 'CommonController@proceed_to_payment')->name('proceed_to_payment');




Route::get('add-channel-id', 'CommonController@add_channel_id');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'admin']], function () {

    Route::get('profile', 'ProfileController@view')->name('profile');
    Route::post('profile-update/{id}', 'ProfileController@update')->name('profile.update');

    Route::post('change-password/{id}', 'ProfileController@changePassword')->name('change.password');
    
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('run_command', 'DashboardController@run_command')->name('run_command');
    Route::get('users', 'UserController@index')->name('users.index');
    Route::get('users/show/{id}', 'UserController@show')->name('user.show');
    Route::get('users/edit/{id}', 'UserController@edit')->name('user.edit');
    Route::put('users/update/{id}', 'UserController@update')->name('user.update');
    Route::get('users/destroy/{id}', 'UserController@edit')->name('user.destroy');
    Route::post('active_deactive','UserController@active_deactive')->name('active_deactive');
    Route::post('active_deactive_store_board','UserController@active_deactive_store_board')->name('active_deactive_store_board');

    // Route::post('active_deactive_school','SchoolController@active_deactive_school')->name('active_deactive_school');

    // Route::post('active_deactive_category','CategoryController@active_deactive_category')->name('active_deactive_category');

    //  Route::post('active_deactive_family','FamilyController@active_deactive_family')->name('active_deactive_family');
    
    Route::resource('board',BoardController::class);   
    Route::resource('store',StoreController::class);    
    Route::resource('category',CategoryController::class);  
    Route::resource('measurement',MeasurementController::class);    
    Route::resource('school',SchoolController::class);  
    Route::resource('issue',IssueController::class);    
    Route::resource('grade',GradeController::class);    
    Route::resource('banner',BannerController::class);
    Route::resource('orders',OrderController::class); 
    Route::resource('family',FamilyController::class);  
    Route::resource('product',ProductController::class);    
    Route::resource('inventory',InventoryController::class);  
    Route::post('data-active-store', 'InventoryController@get_store_data');  
    
    Route::post('product/addstore/{id}', 'ProductController@addstore')->name('product.addstore');   
    Route::get('remove_product_store/{id}', 'ProductController@remove_product_store')->name('remove_product_store');   
    Route::post('save_product_store', 'ProductController@save_product_store')->name('save_product_store');   
    // Route::post('active_deactive_product','ProductController@active_deactive_product')->name('active_deactive_product');
    Route::post('get_image','ProductController@get_image')->name('get_image');

    Route::post('order_notification_customer','OrderController@order_notification_customer')->name('order_notification_customer');
    
    Route::get('reported/issue','IssueController@reported_issue_index')->name('reported.issue');
    Route::get('bulk/notification',[NotificationController::class,'index'])->name('bulk.index');
    Route::post('bulk/notification',[NotificationController::class,'store'])->name('bulk.store');
    
    Route::get('system/config','SystemConfigController@index')->name('system.config');
    Route::post('system/config/submit','SystemConfigController@update')->name('system.config.submit');
    Route::post('system/config/backup','SystemConfigController@update')->name('system.config.backup');
    Route::post('system/config/download','SystemConfigController@update')->name('system.config.download');
    Route::post('system/config/delete_backup','SystemConfigController@update')->name('system.config.delete_backup');
    
    Route::get('app/config','SystemConfigController@app')->name('app.config');
    Route::post('app/config/submit','SystemConfigController@submit_app')->name('app.config.submit');

    Route::get('report/all_report','ReportController@index')->name('report.all');

    Route::get('order/all_orders','OrderController@all_orders')->name('order.all');

    Route::get('order/create_order','OrderController@create_order')->name('order.create');

    Route::post('order/get_user','OrderController@get_user')->name('order.get_user');
    Route::post('order/get_meal','OrderController@get_meal')->name('order.get_meal');
    Route::post('order/get_meal_details','OrderController@get_meal_details')->name('order.get_meal_details');
    Route::post('order/book_meal','OrderController@book_meal')->name('order.book_meal');

    Route::get('order/refund','OrderController@refund')->name('order.refund');
    Route::get('order/all_orders/view/{id}','OrderController@all_orders_view')->name('order.all.view');
    Route::post('refund','OrderController@refund_test')->name('refund');

    Route::any('send-mail-store',[SendMailController::class,'store'])->name('mail.store');
    Route::any('send-mail-board',[SendMailController::class,'board'])->name('mail.board');
    Route::any('send-mail-customer',[SendMailController::class,'customer'])->name('mail.customer');

    Route::any('terms-conditions',[CMSController::class,'terms_conditions'])->name('terms_conditions');
    Route::any('privacy-policy',[CMSController::class,'privacy_policy'])->name('privacy_policy');
    Route::any('interest-bases-ads',[CMSController::class,'interest_bases_ads'])->name('interest_bases_ads');
    Route::any('education-out-reach',[CMSController::class,'education_out_reach'])->name('education_out_reach');
});
Route::group(['namespace' => 'Board', 'prefix' => 'board', 'as' => 'board.', 'middleware' => ['auth', 'board']], function () {
    
    Route::get('profile', 'ProfileController@view')->name('profile');
    Route::post('profile-update/{id}', 'ProfileController@update')->name('profile.update');
    
    Route::post('change-password/{id}', 'ProfileController@changePassword')->name('change.password');
    
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::post('active_deactive_category','CategoryController@active_deactive_category')->name('active_deactive_category');
    Route::resource('category', CategoryController::class);
    Route::resource('store', StoreController::class);
    Route::resource('banner', BannerController::class);
    Route::resource('product', ProductController::class);
    Route::resource('orders',OrderController::class);
    Route::resource('meal', MealController::class);
    Route::post('order_notification_customer','OrderController@order_notification_customer')->name('order_notification_customer');

    Route::get('report/all_report','ReportController@all_report')->name('report.all');
    
    Route::get('order/all','OrderController@all')->name('order.all');
    Route::get('order/all/view/{id}','OrderController@all_orders_view')->name('order.all.view');

    Route::get('order/inprocess','OrderController@inprocess')->name('order.inprocess');
    Route::get('order/inprocess/view/{id}','OrderController@inprocess_view')->name('order.inprocess.view');
    Route::get('order/inprocess/edit/{id}','OrderController@inprocess_edit')->name('order.inprocess.edit');
    Route::post('order/inprocess/item/update','OrderController@item_update')->name('order.item.update');
    Route::post('order/inprocess/date/update','OrderController@date_update')->name('order.date.update');

     Route::post('active_deactive_product','ProductController@active_deactive_product')->name('active_deactive_product');
     Route::post('active_deactive_meal','MealController@active_deactive_meal')->name('active_deactive_meal');

    Route::post('pending_order','OrderController@pending_order')->name('pending_order');

    Route::get('order/completed','OrderController@completed')->name('order.completed');
    Route::get('order/completed/view/{id}','OrderController@completed_view')->name('order.completed.view');

    Route::get('order/fail','OrderController@fail')->name('order.fail');
    Route::get('order/fail/view/{id}','OrderController@fail_view')->name('order.fail.view');


});

Route::group(['namespace' => 'Store', 'prefix' => 'store', 'as' => 'store.', 'middleware' => ['auth', 'store']], function () {
    
    Route::get('profile', 'ProfileController@view')->name('profile');
    Route::post('profile-update/{id}', 'ProfileController@update')->name('profile.update');
    
    Route::post('change-password/{id}', 'ProfileController@changePassword')->name('change.password');
    

app/Http/Controllers/Admin/BannerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Helpers\CommonHelper;
use Illuminate\Http\Request;
use App\Models\Banner;
use App\Models\User;
use Carbon\Carbon;
use DataTables;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {


       if ($request->ajax())
       {
            $data = Banner::select('*')->orderBy('id','desc')->with('user_name')->get();
            return Datatables::of($data)
            ->addIndexColumn()

            ->addColumn('user_data', function($row) {
                    
                    $user_data = $row['user_id'];
                    return  $user_data;
                })

             ->addColumn('start_date', function($row) {
                
                $start_date= date('m-d-Y', strtotime($row['start_date']));
                return $start_date;
            })

             ->addColumn('end_date', function($row) {
                
                $end_date= date('m-d-Y', strtotime($row['end_date']));
                return $end_date;
            })
            
            ->editColumn('image', function ($row) {
                return '<img class="border rounded p-0" src="'.$row['image'].'" onerror="this.src=/images/default.png" alt="your image" style="height: 70px;width: 100px; object-fit: contain;" id="blah1"/>';
            })
            ->editColumn('action', function ($row)
            {
               $btn = '<a href="'.route('admin.banner.edit',$row['id']).'" class="mr-2"><i class="fa fa-edit"></i></a>';
               $btn .= '<a href="'.route('admin.banner.destroy', $row['id']).'" data-url="banner" data-id="'.$row["id"].'" data-popup="tooltip" onclick="delete_notiflix(this);return false;" data-token="'.csrf_token().'" ><i class="fa fa-trash"></i></a>';
               return $btn;
            })
            ->rawColumns(['image','user_data','date_diff' ,'action'])
            ->make(true);
       }
       else
       {
           $columns = [
            //    ['data' => 'sequence', 'name' => 'sequence','title' => __("Sequence")],
               ['data' => 'id','name' => 'id','title' => "Id"], 
               ['data' => 'image','name' => 'image', 'title' => __("Image"),'searchable'=>false],
               ['data' => 'user_name.first_name','name' => 'user_data.full_name', 'title' => __("Board Name"),'searchable'=>true],
               ['data' => 'start_date','name' => 'start_date', 'title' => __("Start Date"),'searchable'=>true],
               ['data' => 'end_date','name' => 'end_date', 'title' => __("End Date"),'searchable'=>true],
               ['data' => 'date_diff','name' => 'date_diff', 'title' => __("Status"),'searchable'=>true],
               ['data' => 'action', 'name' => 'action','title' => "Action",'searchable'=>false,'orderable'=>false]];
           $params['dateTableFields'] = $columns;
           $params['dateTableUrl'] = route('admin.banner.index');
           $params['dateTableTitle'] = "Banner Management";
           $params['dataTableId'] = time();
           $params['addUrl'] = route('admin.banner.create');
           return view('admin.pages.banner.index',$params);
       }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $params['pageTittle'] = "Add Banner";
        $params['backUrl'] = route('admin.banner.index');
        $data = User::select('users.*')->join('users_group', 'users.id', '=', 'users_group.user_id')->where('users_group.group_id',2)->get();
        return view('admin.pages.banner.post',compact('data'),$params);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $request->validate([
            'start_date' => 'required',
            'end_date' => 'date_format:m-d-Y|after_or_equal:start_date',
            'image'=>'required|image|mimes:jpeg,png,jpg,gif,svg'
            
        ]);

        $dir = "images/banner";
        $image = CommonHelper::imageUpload($request->image,$dir);
        $banner = Banner::create([
            'image' => $image,
            'start_date' => Carbon::createFromFormat('m-d-Y', $request->start_date)->format('Y-m-d'),
            'end_date' => Carbon::createFromFormat('m-d-Y', $request->end_date)->format('Y-m-d'),
            'user_id' => $request->user_id,

        ]);
        // dd($banner);
        // redirect
        return redirect()->route('admin.banner.index')->with('success','Banner created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $params['pageTittle'] = "View Banner";
        $banner = Banner::all();
        $params['banner'] = $banner->toArray();
        $params['backUrl'] = route('admin.banner.index');
        return view('admin.pages.banner.view',$params);
    }
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $params['pageTittle'] = "Edit Banner";
        $params['banner'] = Banner::find($id);
        $params['backUrl'] = route('admin.banner.index');
        $data = User::select('users.*')->join('users_group', 'users.id', '=', 'users_group.user_id')->where('users_group.group_id',2)->get();

        return view('admin.pages.banner.put',compact('data'),$params);
    }

    /** 
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $request->validate([
            'start_date' => 'required',
            'end_date' => 'date_format:m-d-Y|after_or_equal:start_date',
            
        ]);

        if(isset($request->image) && $request->image != ''){
            $dir = "images/banner";
            $image = CommonHelper::imageUpload($request->image,$dir);
            $banner['image'] = $image;
        }
        $banner['start_date'] =Carbon::createFromFormat('m-d-Y', $request->start_date)->format('Y-m-d');
        $banner['end_date'] = Carbon::createFromFormat('m-d-Y', $request->end_date)->format('Y-m-d');
        $banner['user_id']=$request->user_id;
        Banner::whereId($id)->update($banner);
        return redirect()->route('admin.banner.index')
                        ->with('success','Banner updated successfully');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Banner::whereId($id)->delete();
        return redirect()->route('admin.banner.index')
                        ->with('success','Banner deleted successfully');
    }

}

resources/views/store/pages/banner/index.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                {{ Breadcrumbs::render('banner')}}
                </div>
                <h4 class="page-title">{{$dateTableTitle}}</h4>
            </div>
            <div class="btn-group float-right mt-2 mb-2">
                    <a href="{{$addUrl}}"  class="btn btn-sm btn-primary waves-effect waves-light">
                    <span class="btn-label">
                        <i class="fa fa-plus"></i>
                    </span>
                    Add
                </a>
            </div>
		</div>
	</div>
    @include('admin.include.flash-message')
	<div class="row">
		<div class="col-xl-12">
			<div class="card">
				<div class="card-body" >
					@include('admin.include.table')
				</div>
			</div>	
		</div>
	</div>
</div>


@endsection
@section('script')

@include('admin.include.table_script')
@endsection		

resources/views/store/pages/banner/post.blade.php
@extends('admin.layouts.master')
@section('css')
<link href="{{ URL::asset('assets/css/bootstrap-datepicker.min.css')}}" rel="stylesheet" type="text/css" />
@endsection
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                {{ Breadcrumbs::render('addbanner')}}
                </div>
                <h4 class="page-title">{{$pageTittle}}</h4>
            </div>
		</div>
	</div>
	<div class="row">
		<div class="col-xl-6">
			<div class="card">
				<div class="card-body" >
                <form action="{{ route('admin.banner.store') }}" method="POST"  enctype="multipart/form-data">
                @csrf
                @method('POST')

                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="parent_id">Select Board<span class="text-danger">*</span></label>
                                <select class="form-control select2" data-parsley-errors-container="#parent_error" value="{{old('user_id')}}" name="user_id" id="user_id" data-placeholder="Select Board" required>
                                    <option selected disabled></option>
                                @if(isset($data) && count($data) > 0)
                                    @foreach($data as $board)
                                    <option value="{{$board->id}}">{{$board->first_name}}</option>
                                    @endforeach
                                @endif
                                </select>
                                <div id="parent_error"></div>
                                @error('user_id')
                                    <div class="error">{{$message}}</div>
                                @enderror
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group ">
                                <label for="image">Start Date<span class="text-danger">*</span></label>
                                <input type="text"  id="datepicker" name="start_date" parsley-trigger="change" value="{{old('start_date')}}" required placeholder="Enter Start Date" class="form-control depature_datepicker" id="name" autocomplete="off">
                                @error('start_date')
                                    <div class="error">{{ $message }}</div>
                                @enderror        
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group ">
                                <label for="image">End Date<span class="text-danger">*</span></label>
                                <input type="text" name="end_date" parsley-trigger="change" value="{{old('end_date')}}" required placeholder="Enter End Date" class="form-control depature_datepicker" id="name" autocomplete="off">
                                @error('end_date')
                                    <div class="error">{{ $message }}</div>
                                @enderror        
                            </div>
                        </div>

                      
                        <div class="col-lg-12">
                            <div class="form-group ">
                                <label for="image">Image<span class="text-danger">*</span></label>
                                <input type="file"  data-parsley-max-file-size="5" required data-parsley-trigger="change" data-parsley-filemimetypes="image/jpeg, image/png" accept="image/*" data-parsley-file-mime-types-message="Only allowed jpeg & png files" onchange="readURL1(this);" id="image" name="image" class="form-control" />
                                @error('image')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                            @php
                                $default = '/images/default.png';
                            @endphp
                                <img class="border rounded p-0"  src="" onerror="this.src='{{$default}}'" alt="your image" style="height: 130px;width: 130px; object-fit: cover;" id="blah1"/>
                            </div>
                        </div>
                    </div>
                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary waves-effect waves-light" type="submit">
                            Submit
                        </button>
                        <button type="reset" class="btn btn-secondary waves-effect m-l-5">
                            Cancel
                        </button>
                    </div>

                </form>

				</div>
			</div>	
		</div>
	</div>
</div>
@endsection
@section('script')
<script type="text/javascript">
function readURL1(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah1').attr('src', e.target.result);
            $('.blah1').attr('href', e.target.result);
        };
        reader.readAsDataURL(input.files[0]);
    }
}
</script>
@endsection

resources/views/store/pages/banner/put.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                {{ Breadcrumbs::render('editbanner')}}
                </div>
                <h4 class="page-title">{{$pageTittle}}</h4>
            </div>
		</div>
	</div>
	<div class="row">
		<div class="col-xl-6">
			<div class="card">
				<div class="card-body" >
                <form action="{{ route('admin.banner.update',$banner->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                    <div class="row">

                        <div class="col-12">
                            <div class="form-group">
                                <label for="parent_id">Select Board<span class="text-danger">*</span></label>
                                <select class="form-control select2" data-parsley-errors-container="#parent_error"  name="user_id" id="user_id" data-placeholder="Select Board" required>
                                <option selected disabled></option>
                                @if(isset($data) && count($data) > 0)
                                    @foreach($data as $board)
                                    <option value="{{$board->id}}" {{$banner->user_id == $board->id  ? 'selected' : ''}}>{{$board->first_name}}</option>
                                    @endforeach
                                @endif
                                    
                                </select>
                                <div id="parent_error"></div>
                                @error('user_id')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                         <div class="col-lg-12">
                            <div class="form-group ">
                                <label for="image">Start Date<span class="text-danger">*</span></label>
                                <input type="text"  id="datepicker" name="start_date" parsley-trigger="change" value="{{date('d-m-Y', strtotime($banner->start_date))}}" required placeholder="Enter Start Date" class="form-control depature_datepicker" id="name">
                                @error('start_date')
                                    <div class="error">{{ $message }}</div>
                                @enderror        
                            </div>
                        </div>

                         <div class="col-lg-12">
                            <div class="form-group ">
                                <label for="image">End Date<span class="text-danger">*</span></label>
                                <input type="text" name="end_date" parsley-trigger="change"  value="{{date('d-m-Y', strtotime($banner->end_date))}}" required placeholder="Enter End Date" class="form-control depature_datepicker" id="name">
                                @error('end_date')
                                    <div class="error">{{$message}}</div>
                                @enderror        
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-group">
                                <label for="image">Image<span class="text-danger">*</span></label>
                                <input type="file" data-parsley-max-file-size="5" data-parsley-trigger="change" data-parsley-filemimetypes="image/jpeg, image/png" accept="image/*" data-parsley-file-mime-types-message="Only allowed jpeg & png files" onchange="readURL1(this);" id="image" name="image" class="form-control" />
                                @error('image')
                                <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                @php
                                $default = '/images/default.png';
                                @endphp
                                <img class="border rounded p-0"  src="{{$banner->image}}" onerror="this.src='{{$default}}'" alt="your image" style="height: 130px;width: 130px; object-fit: cover;" id="blah1"/>
                            </div>
                        </div>
                    </div>

                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary waves-effect waves-light" type="submit">
                            Submit
                        </button>
                        <a href="{{ route('admin.banner.index') }}" class="btn btn-secondary waves-effect m-l-5">Cancel</a>
                        <!-- <button type="reset" class="btn btn-secondary waves-effect m-l-5">
                            Cancel
                        </button> -->
                    </div>

                </form>

				</div>
			</div>	
		</div>
	</div>
</div>


@endsection
@section('script')
<script type="text/javascript">
function readURL1(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah1').attr('src', e.target.result);
            $('.blah1').attr('href', e.target.result);
        };
        reader.readAsDataURL(input.files[0]);
    }
}
</script>
@endsection

resources/views/store/pages/banner/view.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Dashboard</a></li>
                        <li class="breadcrumb-item active">{{$pageTittle}}</li>
                    </ol>
                </div>
                <h4 class="page-title">{{$pageTittle}}</h4>
            </div>
            <div class="btn-group float-right mt-2 mb-2">
                    <a href="{{$backUrl}}"  class="btn btn-secondary waves-effect waves-light">
                    <span class="btn-label">
                        <i class="fa fa-arrow-left"></i>
                    </span>
                    Back
                </a>
            </div>
		</div>
	</div>
	<div class="row">
		<div class="col-xl-12">
			<div class="card">
				<div class="card-body" >
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                            <tbody>
                            <tr>
                                <th class="text-nowrap" scope="row">Name</th>
                                <td colspan="5">{{$product->name}}</td>
                            </tr>
                            <tr>
                                <th class="text-nowrap" scope="row">Canteen Name</th>
                                <td colspan="5"><u><a href="{{ route('admin.canteen.show',$product->canteen_id) }}"> {{$product->canteen_name}}</a></u></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
			</div>	
		</div>
	</div>
</div>


@endsection