routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// use App\Http\Controllers\Admin\UserController;
// use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Admin\SendMailController;
use App\Http\Controllers\Admin\CMSController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::get('home', 'Website\HomeController@index')->name('home');
Route::post('store_list', 'Website\HomeController@store_list')->name('store_list');
Route::get('deals', 'Website\HomeController@deals')->name('deals');
Route::get('store-detail/{id}', 'Website\HomeController@store_detail')->name('store_detail');
Route::post('search_product', 'Website\HomeController@search_product')->name('search_product');
Route::post('add_remove_fav_store', 'Website\FavoriteStoreController@add_remove_fav_store')->name('add_remove_fav_store');
Route::get('products/{id}/{category}', 'Website\HomeController@product_view_all')->name('product_view_all');


Route::post('add_remove_fav_product', 'Website\FavoriteController@add_remove_fav_product')->name('add_remove_fav_product');
Route::get('signup', 'Website\HomeController@signup')->name('signup');
Route::post('register_customer', 'Website\HomeController@register_customer')->name('register_customer');
Route::get('send_otp', 'Website\HomeController@send_otp')->name('send_otp');
Route::post('send_otp_mobile', 'Website\HomeController@send_otp_mobile')->name('send_otp_mobile');
Route::get('product/{id}/{id1}', 'Website\HomeController@product')->name('product');

Route::post('add-to-cart', 'Website\CartController@add_to_cart');
Route::post('notification', 'Website\AccountController@notification')->name('notification');
  
Route::group(['namespace' => 'Website', 'middleware' => ['customer']], function () {
    Route::get('account', 'AccountController@index')->name('account');
   
    Route::post('update', 'AccountController@update')->name('update');
    Route::post('notification_toggle', 'AccountController@notification_toggle')->name('notification_toggle');
  
    Route::get('orders/{type}', 'OrderController@index')->name('orders');
    Route::get('order/detail/{id}', 'OrderController@detail')->name('order_details');
    Route::get('order/here/{id}', 'OrderController@i_am_here');
    Route::resource('address',AddressController::class);          
    Route::any('add-address', 'AddressController@add')->name('add_address');    
    Route::post('delete_address', 'AddressController@delete')->name('delete_address');
    Route::get('cart', 'CartController@index')->name('cart');
    Route::get('checkout', 'CartController@checkout')->name('checkout');
    Route::post('place_order', 'CartController@place_order')->name('place_order');
    Route::post('cart_delete/{id}', 'CartController@destroy');
    Route::post('qty_update', 'CartController@qty_update')->name('qty_update');
    Route::get('cart_verify', 'CartController@cart_verify')->name('cart_verify');
   
	Route::get('favorite', 'FavoriteController@index')->name('favorite');
});

Route::get('education-outreach', 'Api\DocumentController@education_outreach');
Route::get('contact-us', 'Api\DocumentController@contact_us')->name('contact-us');
Route::get('about-us', 'Website\AboutUsController@index')->name('about-us');
Route::get('internet-based-ads', 'Api\DocumentController@internet_based_ads');
Route::get('privacy-notice', 'Api\DocumentController@privacy_notice');
Route::get('term-of-service', 'Api\DocumentController@term_of_service');

Route::post('add-channel-id', 'CommonController@add_channel_id');
Route::get('account-activation/{id}', 'CommonController@account_activation');
Route::any('create/password/{id}/{token}', 'CommonController@craete_password')->name('create.password');
Route::get('auth-account-activation/{id}', 'CommonController@auth_account_activation');

Route::post('forgot/password', 'CommonController@forgot_password')->name('forgot_password');
Route::get('store-forgot-password', 'CommonController@store_forgot_password')->name('store.forgot');
Route::get('board-forgot-password', 'CommonController@board_forgot_password')->name('board.forgot');
Route::get('customer-forgot-password', 'CommonController@customer_forgot_password')->name('customer.forgot');
Route::post('send_email_otp', 'CommonController@send_email_otp')->name('send_email_otp');

Route::get('/', 'Website\HomeController@index');
Route::get('auto_reject_order', 'CronController@auto_reject_order')->name('auto_reject_order');
Route::get('order_failed', 'CronController@order_failed')->name('order_failed');
Route::get('both_reject', 'CronController@both_reject')->name('both_reject');
Route::get('order_expire', 'CronController@order_expire')->name('order_expire');
Route::get('diet_station', 'CronController@diet_station');
Route::get('invoice/pdf/{id}','InvoiceController@pdf');
Route::get('reminder', 'CronController@reminder');
Route::get('test_booky', 'CronController@test_booky');
Route::get('generate_token/{id}', 'CommonController@generate_token')->name('generate_token');
Route::post('make_payment', 'CommonController@make_payment')->name('make_payment');
Route::get('transaction_fail/{id}', 'CommonController@transaction_fail')->name('transaction_fail');
Route::get('transaction_success/{id}/{id1}', 'CommonController@transaction_success')->name('transaction_success');
// Route::get('transaction_success/{id}', 'CommonController@transaction_success')->name('transaction_success');
Route::get('refund/{id}/{id1}', 'CommonController@refund')->name('refund');
Route::get('payment/card', 'CommonController@save_card')->name('save_card');
Route::post('proceed_to_payment', 'CommonController@proceed_to_payment')->name('proceed_to_payment');




Route::get('add-channel-id', 'CommonController@add_channel_id');

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'admin']], function () {

    Route::get('profile', 'ProfileController@view')->name('profile');
    Route::post('profile-update/{id}', 'ProfileController@update')->name('profile.update');

    Route::post('change-password/{id}', 'ProfileController@changePassword')->name('change.password');
    
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::get('run_command', 'DashboardController@run_command')->name('run_command');
    Route::get('users', 'UserController@index')->name('users.index');
    Route::get('users/show/{id}', 'UserController@show')->name('user.show');
    Route::get('users/edit/{id}', 'UserController@edit')->name('user.edit');
    Route::put('users/update/{id}', 'UserController@update')->name('user.update');
    Route::get('users/destroy/{id}', 'UserController@edit')->name('user.destroy');
    Route::post('active_deactive','UserController@active_deactive')->name('active_deactive');
    Route::post('active_deactive_store_board','UserController@active_deactive_store_board')->name('active_deactive_store_board');

    // Route::post('active_deactive_school','SchoolController@active_deactive_school')->name('active_deactive_school');

    // Route::post('active_deactive_category','CategoryController@active_deactive_category')->name('active_deactive_category');

    //  Route::post('active_deactive_family','FamilyController@active_deactive_family')->name('active_deactive_family');
    
    Route::resource('board',BoardController::class);   
    Route::resource('store',StoreController::class);    
    Route::resource('category',CategoryController::class);  
    Route::resource('measurement',MeasurementController::class);    
    Route::resource('school',SchoolController::class);  
    Route::resource('issue',IssueController::class);    
    Route::resource('grade',GradeController::class);    
    Route::resource('banner',BannerController::class);
    Route::resource('orders',OrderController::class); 
    Route::resource('family',FamilyController::class);  
    Route::resource('product',ProductController::class);    
    Route::resource('inventory',InventoryController::class);  
    Route::post('data-active-store', 'InventoryController@get_store_data');  
    
    Route::post('product/addstore/{id}', 'ProductController@addstore')->name('product.addstore');   
    Route::get('remove_product_store/{id}', 'ProductController@remove_product_store')->name('remove_product_store');   
    Route::post('save_product_store', 'ProductController@save_product_store')->name('save_product_store');   
    // Route::post('active_deactive_product','ProductController@active_deactive_product')->name('active_deactive_product');
    Route::post('get_image','ProductController@get_image')->name('get_image');

    Route::post('order_notification_customer','OrderController@order_notification_customer')->name('order_notification_customer');
    
    Route::get('reported/issue','IssueController@reported_issue_index')->name('reported.issue');
    Route::get('bulk/notification',[NotificationController::class,'index'])->name('bulk.index');
    Route::post('bulk/notification',[NotificationController::class,'store'])->name('bulk.store');
    
    Route::get('system/config','SystemConfigController@index')->name('system.config');
    Route::post('system/config/submit','SystemConfigController@update')->name('system.config.submit');
    Route::post('system/config/backup','SystemConfigController@update')->name('system.config.backup');
    Route::post('system/config/download','SystemConfigController@update')->name('system.config.download');
    Route::post('system/config/delete_backup','SystemConfigController@update')->name('system.config.delete_backup');
    

app/Http/Controllers/Board/BannerController.php
<?php

namespace App\Http\Controllers\board;

use App\Http\Controllers\Controller;
use App\Helpers\CommonHelper;
use Illuminate\Http\Request;
use App\Models\Banner;
use App\Models\User;
use DataTables;
use Illuminate\Support\Facades\Auth;


class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
           
           
       if ($request->ajax())
       {
            
             $login_id =  Auth::user()->id;
            $data = Banner::select('*')->where('user_id',$login_id)->orderBy('id','desc')->with('user_name')->get();
            return Datatables::of($data)
            ->addIndexColumn()

            ->addColumn('user_data', function($row) {
                    
                    $user_data = $row['user_id'];
                    return  $user_data;
                })

            ->addColumn('start_date', function($row) {
                
                $start_date= date('m-d-Y', strtotime($row['start_date']));
                return $start_date;
            })

             ->addColumn('end_date', function($row) {
                
                $end_date= date('m-d-Y', strtotime($row['end_date']));
                return $end_date;
            })
            
            ->editColumn('image', function ($row) {
                return '<img class="border rounded p-0" src="'.$row['image'].'" onerror="this.src=/images/default.png" alt="your image" style="height: 70px;width: 100px; object-fit: cover;" id="blah1"/>';
            })
           
            ->editColumn('action', function ($row)
            {
               $btn = '<a href="'.route('board.banner.show',$row['id']).'" class="mr-2"><i class="fa fa-eye"></i></a>';
               // $btn .= '<a href="'.route('board.banner.destroy', $row['id']).'" data-url="banner" data-id="'.$row["id"].'" data-popup="tooltip" onclick="delete_notiflix(this);return false;" data-token="'.csrf_token().'" ><i class="fa fa-trash"></i></a>';
               return $btn;
            })
            ->rawColumns(['image','user_data', 'action'])
            ->make(true);
       }
       else
       {
           $columns = [
            //    ['data' => 'sequence', 'name' => 'sequence','title' => __("Sequence")],
               ['data' => 'id','name' => 'id','title' => "Id"], 
               ['data' => 'image','name' => 'image', 'title' => __("Image"),'searchable'=>false],
               ['data' => 'start_date','name' => 'start_date', 'title' => __("Start Date"),'searchable'=>true],
               ['data' => 'end_date','name' => 'end_date', 'title' => __("End Date"),'searchable'=>true],
               ['data' => 'action', 'name' => 'action','title' => "Action",'searchable'=>false,'orderable'=>false]];
           $params['dateTableFields'] = $columns;
           $params['dateTableUrl'] = route('board.banner.index');
           $params['dateTableTitle'] = "Banner";
           $params['dataTableId'] = time();
           $params['addUrl'] = route('board.banner.create');
           return view('board.pages.banner.index',$params);
       }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $params['pageTittle'] = "View Banner";
        $banner =Banner::find($id);
        // dd($banner);
        $params['banner'] = $banner->toArray();
        $params['backUrl'] = route('board.banner.index');
        return view('board.pages.banner.view',compact('banner'),$params);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Board/DashboardController.php
<?php
namespace App\Http\Controllers\Board;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use CommonHelper;
use Illuminate\Support\Facades\Auth;
use App\Models\Category;
use App\Models\Product;
use App\Models\Meal;
use App\Models\User;
use App\Models\Orders;
use App\Models\StoresProduct;

class DashboardController extends Controller {
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {

        $login_id =  Auth::user()->id;
        // dd($login_id);
        $store = User::select('id')->where('parent_id',$login_id)->get()->pluck('id')->toArray();
        // dd($store); 
        $orders_completed=Orders::whereIn('store_id',$store)->where('status','6')->count();
        // dd($orders);
        
        $total=Orders::whereIn('store_id',$store)->sum('total');

        $customers=User::where('parent_id',$login_id)->count();

        
        $orders = Orders::whereIn('store_id',$store)->count();
        // dd($orders);
        
        $params['store'] = User::select('*')->where('parent_id',$login_id)->count();
        // dd($params['store']);
        $params['product'] = Product::count();
        return view('board.pages.dashboard',compact('orders_completed','total','customers','orders'),$params);
    }
}

resources/views/admin/pages/board/index.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    {{ Breadcrumbs::render('board')}}
                </div>
                <h4 class="page-title">{{$dateTableTitle}}</h4>
            </div>
            <div class="btn-group float-right mt-2 mb-2">
                    <a href="{{$addUrl}}"  class="btn btn-sm btn-primary waves-effect waves-light">
                    <span class="btn-label">
                        <i class="fa fa-plus"></i>
                    </span>
                    Add
                </a>
            </div>
		</div>
	</div>
    @include('admin.include.flash-message')
	<div class="row">
		<div class="col-xl-12">
			<div class="card">
				<div class="card-body" >
					@include('admin.include.table')
				</div>
			</div>	
		</div>
	</div>
</div>
@endsection
@section('script')
@include('admin.include.table_script')
@endsection		

resources/views/admin/pages/board/old_view.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                {{ Breadcrumbs::render('viewboard')}}
                </div>
                <h4 class="page-title">{{$pageTittle}}</h4>
            </div>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-4 col-xl-4">
            <div class="card-box text-center">
                <img src="{{env('AWS_S3_URL').$user['profile_picture']}}" class="rounded-circle avatar-lg img-thumbnail"
                    alt="profile-image">

                <h4 class="mb-0">{{$user['first_name']}} {{$user['last_name']}}</h4>
                <p class="text-muted">{{$user['email']}}</p>

                <div class="text-left mt-3">
                    <h4 class="font-13 text-uppercase">About Me :</h4>
                    <p class="text-muted mb-2 font-13"><strong>First Name :</strong> <span class="ml-2">{{$user['first_name']}}</span></p>

                    <p class="text-muted mb-2 font-13"><strong>Last Name :</strong> <span class="ml-2">{{$user['last_name']}}</span></p>

                    <p class="text-muted mb-2 font-13"><strong>Phone :</strong><span class="ml-2">{{$user['phone_formatted']}}</span></p>

                    <p class="text-muted mb-2 font-13"><strong>Email :</strong> <span class="ml-2">{{$user['email']}}</span></p>
                </div>
            </div> <!-- end card-box -->


        </div> <!-- end col-->

        <div class="col-lg-8 col-xl-8">
            <div class="card-box">
                <ul class="nav nav-pills navtab-bg nav-justified">
                    <li class="nav-item">
                        <a href="#school" data-toggle="tab" aria-expanded="false" class="nav-link">
                            Schools
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#category" data-toggle="tab" aria-expanded="true" class="nav-link active">
                            Category
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#product" data-toggle="tab" aria-expanded="false" class="nav-link">
                            Product
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane" id="school">

                        <div class="table-responsive">
                            <table class="table table-borderless mb-0"  id="school_table">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach ($user['canteen_school'] as $school)
                                <tr>
                                        <td>{{$school['id']}}</td>
                                        <td><u><a href="{{route('admin.school.show',$school['id'])}}"> {{$school['name']}}</a></u></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>

                    </div> <!-- end tab-pane -->
                    <!-- end about me section content -->
                    <div class="tab-pane show active" id="category">

                    <div class="table-responsive">
                            <table class="table table-borderless mb-0"  id="category_table">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach ($user['category'] as $category)
                                <tr>
                                        <td>{{$category['id']}}</td>
                                        <td>{{$category['name']}}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>

                    </div>
                    <!-- end timeline content-->

                    <div class="tab-pane" id="product">
                    <div class="table-responsive">
                            <table class="table table-borderless mb-0"  id="product_table">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Id</th>
                                        <th>Name</th>
                                        <th>Category Name</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach ($user['product'] as $product)
                                <tr>
                                        <td>{{$product['id']}}</td>
                                        <td>{{$product['name']}}</td>
                                        <td>{{$product['category_name']}}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>

                    </div>
                    </div>
                    <!-- end settings content-->

                </div> <!-- end tab-content -->
            </div> <!-- end card-box-->

        </div> <!-- end col -->
    </div>
</div>

@endsection
@section('script')
@include('admin.include.table_script_multiple')
<script type="text/javascript">
$(function() {
    $('#school_table').DataTable();
    $('#category_table').DataTable();
    $('#product_table').DataTable();
});
</script>
@endsection	

resources/views/admin/pages/board/put.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    {{ Breadcrumbs::render('editboard')}}
                </div>
                <h4 class="page-title">{{$pageTittle}}</h4>
            </div>
		</div>
	</div>
	<div class="row">
		<div class="col-xl-6">
			<div class="card">
				<div class="card-body" >
                <form action="{{ route('admin.board.update',$user->id) }}" method="POST"  enctype="multipart/form-data">
                @csrf
                @method('PUT')

                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="first_name">Board Name<span class="text-danger">*</span></label>
                                <input type="text" name="first_name" parsley-trigger="change" value="{{$user->first_name}}" required placeholder="Enter Board Name" class="form-control" id="first_name">
                                @error('first_name')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label for="email">Email address<span class="text-danger">*</span></label>
                                <input type="email" name="email" parsley-trigger="change" value="{{$user->email}}" required placeholder="Enter email" class="form-control" id="email" readonly>
                                @error('email')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label for="phone">Phone<span class="text-danger">*</span></label>
                                <input type="text" name="phone" parsley-trigger="change" value="{{$user->phone}}" required  class="form-control" id="phone" readonly>
                                @error('phone')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>

                        <div class="col-12">
                            <div class="form-group">
                                <label for="image">Image<span class="text-danger">*</span></label>
                                <input type="file" data-parsley-trigger="change"  data-parsley-max-file-size="5" data-parsley-filemimetypes="image/jpeg, image/png" accept="image/*" data-parsley-file-mime-types-message="Only allowed jpeg & png files" onchange="readURL1(this);" id="image" name="image" class="form-control" />
                                @error('image')
                                    <div class="error">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                        <div class="col-lg-6"> 
                            <div class="form-group">
                            @php
                                $default = '/images/default.png';
                            @endphp
                                <img class="border rounded p-0"  src="{{env('AWS_S3_URL').$user->profile_picture}}" onerror="this.src='{{$default}}'" alt="your image" style="height: 130px;width: 130px; object-fit: cover;" id="blah1"/>
                            </div>
                        </div>
                    </div>

                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary waves-effect waves-light" type="submit">
                            Submit
                        </button>
                        <a href="{{ route('admin.board.index') }}" class="btn btn-secondary waves-effect m-l-5">Cancel</a>
                        <!-- <button type="reset" class="btn btn-secondary waves-effect m-l-5">
                            Cancel
                        </button> -->
                    </div>

                </form>

				</div>
			</div>	
		</div>
	</div>
</div>
@endsection
@section('script')
<script type="text/javascript">
function readURL1(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
            $('#blah1').attr('src', e.target.result);
            $('.blah1').attr('href', e.target.result);
        };
        reader.readAsDataURL(input.files[0]);
    }
}
</script>
@endsection

resources/views/admin/pages/board/view.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                {{ Breadcrumbs::render('viewboard')}}
                </div>
                <h4 class="page-title">{{$pageTittle}}</h4>
            </div>
		</div>
	</div>
    <div class="row">
        <div class="col-lg-4 col-xl-4">
            <div class="card-box text-center">
                <img src="{{env('AWS_S3_URL').$user['profile_picture']}}" class="rounded-circle avatar-lg img-thumbnail"
                    alt="profile-image">

                <h4 class="mb-0">{{$user['first_name']}}</h4>
                <p class="text-muted">{{$user['email']}}</p>

                <div class="text-left mt-3">
                    <!-- <h4 class="font-13 text-uppercase">About Me :</h4> -->
                    <p class="text-muted mb-2 font-13"><strong>Board Name :</strong> <span class="ml-2">{{$user['first_name']}}</span></p>

                    <p class="text-muted mb-2 font-13"><strong>Phone :</strong><span class="ml-2">{{$user['phone_formatted']}}</span></p>

                    <p class="text-muted mb-2 font-13"><strong>Email :</strong> <span class="ml-2">{{$user['email']}}</span></p>
                </div>
            </div> <!-- end card-box -->


        </div> <!-- end col-->

     

        </div> <!-- end col -->
        <div class="row">
        @foreach($banner as $banner)
        <div class="col-xl-3">
            <div class="card">
              <img class="card-img-top"  style="height: 219px;object-fit: contain;" src="{{$banner->image}}" alt="Card image cap">
              <!-- <div class="card-body">
                <h5 class="card-title">Card title</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
              </div> -->
               <ul class="list-group list-group-flush">
                    <li class="list-group-item"> Start Date: {{date('m-d-Y', strtotime($banner->start_date))}} </li>
                    <li class="list-group-item"> End Date : {{date('m-d-Y', strtotime($banner->end_date))}} </li>   
                </ul>
              <!-- <div class="card-body">
                <a href="#" class="card-link">Card link</a>
                <a href="#" class="card-link">Another link</a>
              </div> -->
            </div>
                
        </div>
        @endforeach
           
    </div>

    
    </div>
</div>

@endsection
@section('script')
@include('admin.include.table_script_multiple')
<script type="text/javascript">
$(function() {
    $('#school_table').DataTable();
    $('#category_table').DataTable();
    $('#product_table').DataTable();
});
</script>
@endsection	